templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: simpleReport.jrxml
    attributes:
      map: !map
        maxDpi: 400
        width: 780
        height: 330
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}

  #===========================================================================
  Auto tiling: !template
    #===========================================================================
    reportTemplate: simpleReport.jrxml
    attributes:
      title: !string
        default: ''
      map: !map
        maxDpi: 400
        width: 780
        height: 330
      northArrow: !northArrow
        size: 200
        default:
          graphic: 'north.svg'
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !setTiledWms
      maxWidth: 256
      maxHeight: 256
    - !createMap {}
    - !createNorthArrow {}

  #===========================================================================
  Auto meta tiling: !template
    #===========================================================================
    reportTemplate: report.jrxml
    attributes:
      title: !string
        default: ''
      map: !map
        maxDpi: 400
        width: 1000
        height: 1000
      northArrow: !northArrow
        size: 200
        default:
          graphic: 'north.svg'
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !setTiledWms
      maxWidth: 256
      maxHeight: 256
      tileBufferWidth: 1
      tileBufferHeight: 1
    - !createMap {}
    - !createNorthArrow {}
