throwErrorOnExtraParameters: true
transparentTileErrorColor: 'rgba(78, 78, 255, 125)'
opaqueTileErrorColor: 'rgba(255, 155, 155, 0)'

#http://mapfish.github.io/mapfish-print-doc/configuration.html#!proxy
#proxies:
#  - !proxy
#    scheme: http
#    host: "[::1]"
#    port: 8080
#    username: jack
#    password: insecure
#    # TODO: Try with different URLs in the request and different matchers here
#    preemtiveAuthScheme: Basic
#    matchers:
#      - !acceptAll {}

templates:
  Square: !template
    reportTemplate: report.jrxml
    attributes:
      title: !string
        default: ''
      map: !map
        maxDpi: 400
        width: 256
        height: 256
    processors:
      - !reportBuilder
        directory: '.'
      - !createMap {}
      - !setTiledWms
        maxWidth: 500
        maxHeight: 500
        tileBufferWidth: 50
        tileBufferHeight: 50
 #     - !configureHttpRequests
 #         httpProcessors:
 #         - !addHeaders
 #             headers:
 #               User-Agent: "MapFish Print"
