#!/bin/bash
#
# Usage ./runexample example01 [--debug]
# Will example and print out as pdf/png

DEBUG=""
if [ "$1" == "--debug" ]; then
    DEBUG="--debug-jvm"
fi

#if [ -z $EXAMPLE ]; then
#    echo "Usage: ./runexample example01 [--debug]"
#    exit 1
#fi

TIMESTAMP=`date -u +"%Y-%m-%dT%H%M%S"`
RUN_PATH="$(pwd)"
MFP_PATH=$HOME/dev/mfp/mapfish-print
#MFP_PATH=$HOME/dev/mfp/gradle/mapfish-print

echo "DEBUG=$DEBUG"
echo "RUN_PATH: $RUN_PATH"
echo "MFP_PATH=$MFP_PATH"

cd $MFP_PATH
LOGBACK_CONFIG="-Dlogback.configurationFile=/home/bhoefling/dev/mfp/my-examples/logback-http-debug.xml"

for json in `ls $RUN_PATH/*.json`; do
  echo $json
  INPUT=$json
  OUTPUT=${INPUT%.json}_$TIMESTAMP
  LOG=${INPUT%.json}_$TIMESTAMP.log
  echo $INPUT
  echo $OUTPUT
  $MFP_PATH/gradlew print  "-Dlogback.debug=true" $LOGBACK_CONFIG $DEBUG -PprintArgs="-config $RUN_PATH/config.yaml -spec $INPUT -output $OUTPUT -uselogback" | tee $LOG
done

# ln
