throwErrorOnExtraParameters: true
transparentTileErrorColor: 'rgba(78, 78, 255, 125)'
opaqueTileErrorColor: 'rgba(255, 155, 155, 0)'

templates:
  A4 portrait: !template
    reportTemplate: report.jrxml
    attributes:
      title: !string
        default: 'Countries'
      map: !map
        zoomLevels: !zoomLevels
#          scales: [1000000, 10000000, 100000000]
          scales: [10000000, 100000000]
        maxDpi: 400
        width: 780
        height: 330
    processors:
      - !reportBuilder
        directory: '.'
      - !createMap {}
