throwErrorOnExtraParameters: true
transparentTileErrorColor: 'rgba(78, 78, 255, 125)'
opaqueTileErrorColor: 'rgba(255, 155, 155, 0)'

templates:
  A4 portrait: !template
    reportTemplate: report.jrxml
    attributes:
      timezone: !string
        default: 'GMT-5:00'
      title: !string
        default: 'Countries'
      map: !map
        maxDpi: 400
        width: 780
        height: 330
    processors:
      - !reportBuilder
        directory: '.'
      - !createMap {}
      # Here we add two processors for "dateFormat":
      # The first one is the default one and it will use ISO pattern:
      - !dateFormat
         pattern: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
      # The second one uses a french pattern. We need to remap the
      # output, such that we then have to parameters in the report
      # in order to use both:
      - !dateFormat
        pattern: "EEEEE dd MMMMM yyyy HH:mm"
        outputMapper: {dateFormat: frenchDateformat}
